# Generated by Django 3.2.9 on 2021-12-14 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='applicant_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('center', models.CharField(max_length=30)),
                ('category', models.CharField(max_length=30)),
                ('dob', models.CharField(max_length=30)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('booking_status', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'db_table': 'applicant_data',
            },
        ),
    ]
