# Generated by Django 3.2.9 on 2021-12-14 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('input_fm', '0002_applicants_data'),
    ]

    operations = [
        migrations.DeleteModel(
            name='applicants_data',
        ),
    ]
